### ISSUE TITLE
[Gallery] Gallery tab header content

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#69]
- Font size/weight
- Subtitle info icon with tooltip
- "View your submissions" button

Firefly:
<img width="1728" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/74568ec3-7460-49a3-b184-993033a28c5a">

Franklin:
<img width="1728" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/594a8c70-56be-464f-8db5-66914ca24374">

**Comment by kunwarsaluja** [comment]
fixed with #84

**Comment by tom-hightower** [comment]
This doesn't appear to be fixed. The font size/weight, subtitle info icon with tooltip, and "view your submissions" button are all still issues. Additionally, it looks like the top nav doesn't display on the gallery page?

<img width="1728" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/5140b3db-7338-4b3c-af10-2688e9af204a">

**Comment by kunwarsaluja** [comment]
@tom-hightower are we looking at the same page ? Can you review https://main--firefly--adobecom.hlx.page/community and let me know what are we missing and I can fix those for you.


Other thing I noticed, where are these strings coming from ?
1. Discover Firefly prompts to remix and submit your own images to the gallery. (I found something close [here](https://git.corp.adobe.com/neuralfiltersplatform/spl-web-client/blob/main/packages/clio-playground/src/lang/en-US.json#L1428) but not the same string)
2. As you create with Text to image, use the Share button to make submissions. (tooltip text)

I don't see them in the [en-US.json dictionary](https://git.corp.adobe.com/neuralfiltersplatform/spl-web-client/blob/main/packages/clio-playground/src/lang/en-US.json) ? Are these Hardcoded strings ?

**Comment by tom-hightower** [comment]
Oh sorry, I was looking at the https://main--firefly--adobecom.hlx.live/community version. What is the difference between this and the `.page` version?

The version you linked is closer, but still doesn't match the existing live site. The main issues I see are the spacing, color theming, content (strings that the community gallery team use are [here](https://git.corp.adobe.com/Communities/community-hubs-ui/blob/main/src/lang/en-US.json)), and that the "View your submissions" should only appear for a logged in user.
Firefly:
<img width="1728" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/6480277e-3716-46c8-a6b1-8ab131164527">

Franklin:
<img width="1728" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/b1ddf069-228f-4738-9ce1-9e213fe5aa0c">

**Comment by kunwarsaluja** [comment]
@tom-hightower 
.live is the final published version and .page is more like preview before we actually publish it. 

Spacing and other things are easy fixes and can deal with them  tomorrow morning.

Localized content now in community git repo altogether makes things a bit weird as we were piggybacking on en-us and other localized json in spl-webclient repo as a single source of truth but now we have a new repo that has different set of localized json that too just for the community page wondering if we should create a manual spreadsheet with key value pairs of strings currently being used on homepage and community page rather than trying to reuse the localized jsons from both these repos. Opinions ? Suggestions ?

@kailasnadh790 For the ‘view submission’ button, is there a helper function that we use to check if the user is logged in or not?

**Comment by kunwarsaluja** [comment]
@tom-hightower  Putting this issue on hold until we have clarity if firefly team wants to take just the homepage or both homepage + community page on the new platform. Will pick this up when we have clear direction on that.
